lightningmodule:
  _target_: src.methods.transformer.lightningmodule.TransformerLightningModule
  d_model: 32
  d_ffn: 16
  n_heads: 2
  d_k: 16
  d_v: 16
  n_layers: 1
  dropout: 0.2
  attn_dropout: 0.2
  ORT_weight: 1
  MIT_weight: 1
  lr: 0.002
  clf_weight: 0.5
name: transformer