defaults:
  - model_checkpoint.yaml
  - model_summary.yaml
  # - clf_metrics.yaml
  # - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1
