_target_: lightning.fabric.Fabric
accelerator: auto
strategy: auto
devices: 1
num_nodes: 1
precision: 32
plugins: null
loggers: null

# callbacks:
#     - _target_: cross_validate.ScoreCrossValidationCallback
#       num_classes: 2
#       average: macro