_target_: lightning.pytorch.Trainer
accelerator: cpu
max_epochs: 5
deterministic: true
devices: 4
num_nodes: 1
strategy: 
  _target_: lightning.pytorch.strategies.DDPStrategy
  find_unused_parameters: true