# @package _global_

# specify here default configuration

defaults: 
  - _self_
  - data: daicwoz.yaml
  - model: brits.yaml
  - trainer: fabric.yaml
  - callbacks: cv_eval.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - logger: none.yamls
  - experiment: null

# task name, determines output directory path
task: train
test: false
seed: 42
folds: 3
epochs: 2
dry_run: true
save_model: false
optimized_metric: 'f1'