# @package _global_

# specify here default configuration

defaults: 
  - _self_
  - data: daicwoz.yaml
  - model: usgan.yaml
  - trainer: cpu.yaml
  - callbacks: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - logger: csv.yaml
  - experiment: null
  - extras: default.yaml

# task name, determines output directory path
task: train
test: false
tags: ['default']
seed: 42
optimized_metric: null
extras: true
